# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='relationships',
            field=models.ManyToManyField(blank=True, related_name='related_to', through='users.Relationship', to='users.Profile'),
        ),
    ]
