# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170905_2204'),
        ('blogs', '0002_auto_20170906_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourites', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='blog',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentions', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='blog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='answerComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.Commentary'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='owner',
            field=models.ManyToManyField(to='users.Profile'),
        ),
    ]
