# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_remove_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.Post'),
        ),
    ]
