# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_commentary_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
