# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20171024_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='favourites',
        ),
    ]
